<a href="https://colab.research.google.com/github/MRS88/AI_course/blob/master/%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F_04_Pandas_%D0%A7%D0%B0%D1%81%D1%82%D1%8C_2/Pro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Задача 1: DateTime index

* Подгрузите данные 'data.csv' (возможно придется указать кодировку encoding сp1250) в переменную data.
* Преобразуйте колонку InvoiceDate в DateTime index.
* Удалите колонку InvoiceDate.


**Решение:**

In [ ]:
import pandas as pd

data = pd.read_csv('/content/data.csv', encoding='cp1250')
data.index = pd.to_datetime(data.InvoiceDate)
data.drop('InvoiceDate', axis=1, inplace=True)
data.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

### Задача 2

Используя датафрейм data, выберите все заказы, совершенные за период 7 декабря 2010 года с часа дня до часа и одной минуты.

**Решение:**

In [ ]:
period = data[('2010-12-07 13:00:00' <= data.index) & (data.index <= '2010-12-07 13:01:00')]
period

                    InvoiceNo StockCode  ... CustomerID         Country
InvoiceDate                              ...
2010-12-07 13:01:00    537604     84991  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     21845  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     21534  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     21527  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     21528  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     21843  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     22429  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     22551  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     22557  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     22555  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     22304  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     22305  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     20749  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     22525  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     22524  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     22515  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     22514  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     22518  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     82552  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     20750  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     21212  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     21210  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     22567  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     22558  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     21155  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     22061  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     37446  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     37449  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     22519  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     21754  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     20969  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     20967  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     22570  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     22568  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     22569  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     20971  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     84880  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     82484  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     22173  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     84879  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     21136  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     22185  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     22488  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604     71477  ...    13488.0  United Kingdom
2010-12-07 13:01:00    537604    85123A  ...    13488.0  United Kingdom

[45 rows x 7 columns]

### Задача 3

По той же рабочей табличке:
* посчитайте количество уникальных наименований товаров (Description), которые купили за весь период (т.е. по всем данным). Используйте соответствующий метод.
* найдите все уникальные страны, в которых были размещены заказы.

**Решение:**

In [ ]:
print(period['Description'].nunique())
print(data['Description'].nunique())
data_1 = data.dropna(axis=0, how='any', subset=['Description'])['Country'].unique()
data_1

45
4223

array(['United Kingdom', 'France', 'Australia', 'Netherlands', 'Germany',
       'Norway', 'EIRE', 'Switzerland', 'Spain', 'Poland', 'Portugal',
       'Italy', 'Belgium', 'Lithuania', 'Japan', 'Iceland',
       'Channel Islands', 'Denmark', 'Cyprus', 'Sweden', 'Austria',
       'Israel', 'Finland', 'Bahrain', 'Greece', 'Hong Kong', 'Singapore',
       'Lebanon', 'United Arab Emirates', 'Saudi Arabia',
       'Czech Republic', 'Canada', 'Unspecified', 'Brazil', 'USA',
       'European Community', 'Malta', 'RSA'], dtype=object)

### Задача 4

* Посчитайте матрицу корреляции Спирмена для наших данных.
* Найдите 1%, 50% и 99% квантили цены за единицу товара.

*Для решения данной задачи потребуется самостоятельно найти способ получения матрицы Спирмена. Обратите внимание, на вебинаре продемонстрирован пример матрицы Пирсона.*

**Решение:**

In [ ]:
print(data.corr(method='spearman'))
print()
data['UnitPrice'].quantile([0.01, 0.5, 0.99])

            Quantity  UnitPrice  CustomerID
Quantity    1.000000  -0.385407   -0.141124
UnitPrice  -0.385407   1.000000   -0.013255
CustomerID -0.141124  -0.013255    1.000000

0.01     0.19
0.50     2.08
0.99    18.00
Name: UnitPrice, dtype: float64

### Задача 5

Найдите количество клиентов, которые оформляли заказ в понедельники. Для этого
* сделайте подвыборку, соответствующую условию "в понедельник",
* посчитайте количество уникальных ID клиентов.

*Для решения этой задачи потребуется использовать параметр индекса weekday (по аналогии с рассмотренными на вебинаре примерами .index.month, .index.day)*

**Решение:**

In [ ]:
data[(data.index.day == 1)]['CustomerID'].nunique()